apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: game-manager
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["StatefulSet"]
    verbs: ["get", "list", "patch"]
