apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: game-manager
  namespace: game-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: game-manager
subjects:
  - kind: ServiceAccount
    name: game-manager
